/* This file was generated by llr_xorgf_generator.  */
/*
llr_xorgf_generator has the license below, which
also applies to this generated code, as it contains
substantial parts of llr_xorgf_generator:

Copyright 2022 raid5atemyhomework

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
#include"llr_xorgf_ones.h"

unsigned int const llr_xorgf_ones[256] = {
	0, /* 0x00 */
	8, /* 0x01 */
	11, /* 0x02 */
	19, /* 0x03 */
	14, /* 0x04 */
	22, /* 0x05 */
	21, /* 0x06 */
	29, /* 0x07 */
	17, /* 0x08 */
	25, /* 0x09 */
	24, /* 0x0a */
	32, /* 0x0b */
	23, /* 0x0c */
	31, /* 0x0d */
	30, /* 0x0e */
	38, /* 0x0f */
	20, /* 0x10 */
	20, /* 0x11 */
	29, /* 0x12 */
	29, /* 0x13 */
	26, /* 0x14 */
	26, /* 0x15 */
	35, /* 0x16 */
	35, /* 0x17 */
	25, /* 0x18 */
	25, /* 0x19 */
	30, /* 0x1a */
	30, /* 0x1b */
	31, /* 0x1c */
	31, /* 0x1d */
	40, /* 0x1e */
	40, /* 0x1f */
	24, /* 0x20 */
	22, /* 0x21 */
	21, /* 0x22 */
	19, /* 0x23 */
	34, /* 0x24 */
	32, /* 0x25 */
	31, /* 0x26 */
	29, /* 0x27 */
	29, /* 0x28 */
	27, /* 0x29 */
	26, /* 0x2a */
	24, /* 0x2b */
	35, /* 0x2c */
	33, /* 0x2d */
	36, /* 0x2e */
	34, /* 0x2f */
	26, /* 0x30 */
	32, /* 0x31 */
	25, /* 0x32 */
	31, /* 0x33 */
	32, /* 0x34 */
	38, /* 0x35 */
	27, /* 0x36 */
	33, /* 0x37 */
	31, /* 0x38 */
	37, /* 0x39 */
	30, /* 0x3a */
	36, /* 0x3b */
	41, /* 0x3c */
	47, /* 0x3d */
	40, /* 0x3e */
	46, /* 0x3f */
	27, /* 0x40 */
	23, /* 0x41 */
	24, /* 0x42 */
	20, /* 0x43 */
	25, /* 0x44 */
	21, /* 0x45 */
	18, /* 0x46 */
	14, /* 0x47 */
	38, /* 0x48 */
	34, /* 0x49 */
	35, /* 0x4a */
	31, /* 0x4b */
	32, /* 0x4c */
	28, /* 0x4d */
	29, /* 0x4e */
	25, /* 0x4f */
	33, /* 0x50 */
	37, /* 0x51 */
	28, /* 0x52 */
	32, /* 0x53 */
	27, /* 0x54 */
	31, /* 0x55 */
	22, /* 0x56 */
	26, /* 0x57 */
	36, /* 0x58 */
	40, /* 0x59 */
	31, /* 0x5a */
	35, /* 0x5b */
	34, /* 0x5c */
	38, /* 0x5d */
	33, /* 0x5e */
	37, /* 0x5f */
	27, /* 0x60 */
	33, /* 0x61 */
	34, /* 0x62 */
	40, /* 0x63 */
	25, /* 0x64 */
	31, /* 0x65 */
	32, /* 0x66 */
	38, /* 0x67 */
	34, /* 0x68 */
	40, /* 0x69 */
	37, /* 0x6a */
	43, /* 0x6b */
	24, /* 0x6c */
	30, /* 0x6d */
	31, /* 0x6e */
	37, /* 0x6f */
	31, /* 0x70 */
	29, /* 0x71 */
	40, /* 0x72 */
	38, /* 0x73 */
	29, /* 0x74 */
	27, /* 0x75 */
	34, /* 0x76 */
	32, /* 0x77 */
	42, /* 0x78 */
	40, /* 0x79 */
	47, /* 0x7a */
	45, /* 0x7b */
	40, /* 0x7c */
	38, /* 0x7d */
	45, /* 0x7e */
	43, /* 0x7f */
	29, /* 0x80 */
	37, /* 0x81 */
	24, /* 0x82 */
	32, /* 0x83 */
	25, /* 0x84 */
	33, /* 0x85 */
	20, /* 0x86 */
	28, /* 0x87 */
	28, /* 0x88 */
	36, /* 0x89 */
	23, /* 0x8a */
	31, /* 0x8b */
	20, /* 0x8c */
	28, /* 0x8d */
	11, /* 0x8e */
	19, /* 0x8f */
	43, /* 0x90 */
	43, /* 0x91 */
	36, /* 0x92 */
	36, /* 0x93 */
	35, /* 0x94 */
	35, /* 0x95 */
	32, /* 0x96 */
	32, /* 0x97 */
	34, /* 0x98 */
	34, /* 0x99 */
	27, /* 0x9a */
	27, /* 0x9b */
	30, /* 0x9c */
	30, /* 0x9d */
	23, /* 0x9e */
	23, /* 0x9f */
	37, /* 0xa0 */
	35, /* 0xa1 */
	38, /* 0xa2 */
	36, /* 0xa3 */
	29, /* 0xa4 */
	27, /* 0xa5 */
	34, /* 0xa6 */
	32, /* 0xa7 */
	28, /* 0xa8 */
	26, /* 0xa9 */
	33, /* 0xaa */
	31, /* 0xab */
	20, /* 0xac */
	18, /* 0xad */
	25, /* 0xae */
	23, /* 0xaf */
	37, /* 0xb0 */
	43, /* 0xb1 */
	40, /* 0xb2 */
	46, /* 0xb3 */
	29, /* 0xb4 */
	35, /* 0xb5 */
	32, /* 0xb6 */
	38, /* 0xb7 */
	32, /* 0xb8 */
	38, /* 0xb9 */
	39, /* 0xba */
	45, /* 0xbb */
	32, /* 0xbc */
	38, /* 0xbd */
	35, /* 0xbe */
	41, /* 0xbf */
	28, /* 0xc0 */
	24, /* 0xc1 */
	33, /* 0xc2 */
	29, /* 0xc3 */
	36, /* 0xc4 */
	32, /* 0xc5 */
	41, /* 0xc6 */
	37, /* 0xc7 */
	25, /* 0xc8 */
	21, /* 0xc9 */
	34, /* 0xca */
	30, /* 0xcb */
	33, /* 0xcc */
	29, /* 0xcd */
	38, /* 0xce */
	34, /* 0xcf */
	36, /* 0xd0 */
	40, /* 0xd1 */
	39, /* 0xd2 */
	43, /* 0xd3 */
	36, /* 0xd4 */
	40, /* 0xd5 */
	43, /* 0xd6 */
	47, /* 0xd7 */
	21, /* 0xd8 */
	25, /* 0xd9 */
	28, /* 0xda */
	32, /* 0xdb */
	29, /* 0xdc */
	33, /* 0xdd */
	36, /* 0xde */
	40, /* 0xdf */
	32, /* 0xe0 */
	38, /* 0xe1 */
	27, /* 0xe2 */
	33, /* 0xe3 */
	40, /* 0xe4 */
	46, /* 0xe5 */
	39, /* 0xe6 */
	45, /* 0xe7 */
	29, /* 0xe8 */
	35, /* 0xe9 */
	24, /* 0xea */
	30, /* 0xeb */
	33, /* 0xec */
	39, /* 0xed */
	28, /* 0xee */
	34, /* 0xef */
	42, /* 0xf0 */
	40, /* 0xf1 */
	39, /* 0xf2 */
	37, /* 0xf3 */
	46, /* 0xf4 */
	44, /* 0xf5 */
	43, /* 0xf6 */
	41, /* 0xf7 */
	39, /* 0xf8 */
	37, /* 0xf9 */
	36, /* 0xfa */
	34, /* 0xfb */
	47, /* 0xfc */
	45, /* 0xfd */
	40, /* 0xfe */
	38 /* 0xff */
};
